config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  get 'pages/home', to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :recipes do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :delete]
  end
  
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  resources :ingredients, except: [:destroy]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'

  resources :messages, only: [:create]

end

app/models/chef.rb
class Chef < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :chefname, presence: true, length: {maximum: 30}
    VALID_EMAIL_REGEX = 	
    /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, 
        uniqueness: {case_sensitive: false}
    
    has_many :recipes, dependent: :destroy
    has_secure_password
    validates :password, presence: true, length: { minimum: 5 }, allow_nil: true
    default_scope -> {order(updated_at: :desc)}
    has_many :comments, dependent: :destroy
    has_many :messages, dependent: :destroy
    has_many :likes, dependent: :destroy
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController   
    before_action :set_chef, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:index, :show, :new, :create]
    before_action :require_same_user, only: [:edit, :update, :destroy]
              
    def new
        @chef = Chef.new
    end

    def create
        @chef = Chef.new(chef_params)
        if @chef.save
            session[:chef_id] = @chef.id
            cookies.signed[:chef_id] = @chef.id
            flash[:success] = "Welcome #{@chef.chefname} to MyRecipes App!"
            redirect_to chef_path(@chef)
        else
            render 'new'
        end
    end

    def show
        @chef_recipes = @chef.recipes.paginate(page: params[:page], per_page: 5)
    end

    def index
        @chefs = Chef.paginate(page: params[:page], per_page: 5)
    end

    def edit 
    end

    def update 
        if @chef.update(chef_params)
            flash[:success] = "Your profile was updated"
            redirect_to @chef
        else
            render 'edit'
        end
    end

    def destroy 
        @chef.destroy
        flash[:success] = "Chef and all associated recipes have been deleted"
        redirect_to chefs_path
    end

    private
    def set_chef
        @chef = Chef.find(params[:id])
    end

    def chef_params
        params.require(:chef).permit(:chefname, :email, :password, :password_confirmation)
    end

    def require_same_user 
        if current_chef != @chef and !current_chef.admin?
            flash[:danger] = "You can only edit or delete your own account"
            redirect_to chefs_path
        end
    end

    def require_admin
        if logged_in && !current_chef.admin?
            flash[:danger] = "Only admin users can perform that action"
            redirect_to rooth_path
        end 
    end


end

app/views/chefs/_form.html.erb
 <%= render 'shared/errors', obj:@chef %>
 <div class="card">
     <div class="card-body">
         <%= form_for @chef do |f| %>
         <div class="form-group">
             <%= f.text_field :chefname, class:"form-control form-control-lg", placeholder:"Name"%>
         </div>
         <div class="form-group">
             <%= f.email_field :email, class:"form-control form-control-lg", placeholder:"Email address"%>
         </div>
         <div class="form-group">
             <%= f.password_field :password, class:"form-control form-control-lg", placeholder:"Password"%>
         </div>
         <div class="form-group">
             <%= f.password_field :password_confirmation, class:"form-control form-control-lg", placeholder:"Type Password Again"%>
         </div>
         <div class="text-center my-3">
             <%= f.submit(@chef.new_record? ? 'Create New Account' : 'Update', class:"btn btn-lg btn-success w-50") %>
         </div>
         <% end %>
     </div>
 </div>

app/views/chefs/_login_and_signup_form.html.erb
 <div class="card">
     <div class="card-body">
         <%= form_for :session, url: login_path do |f| %>
         <div class="form-group">
             <%= f.email_field :email, class:"form-control form-control-lg", placeholder:"Email address"%>
         </div>
         <div class="form-group">
             <%= f.password_field :password, class:"form-control form-control-lg", placeholder:"Password"%>
         </div>
         <div class="text-center my-3">
             <%= f.submit 'Log In', class:"btn btn-lg btn-success w-50" %>
         </div>
         <% end %>
         <hr>
         <div class="text-center my-3">
             <%= link_to "Register", signup_path, class: "btn btn-lg btn-danger" %>
         </div>

     </div>
 </div>

app/views/chefs/edit.html.erb
<div class="row">
    <div class="col-md-8 offset-md-2 mb-5">
        <%= render 'form', title: 'Edit Chef' %>
    </div>
</div>

app/views/chefs/index.html.erb
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2 class="mt-3 line">All Chefs</h2>
        <%= will_paginate list_classes: %w(pagination justify-content-center mt-2)%>
        <% @chefs.each do |chef|%>
        <div class="row border-bottom m-3">
            <div class="col-md-2 my-3 text-right">
                <%= link_to gravatar_for(chef), chef_path(chef) %>
            </div>
            <div class="col-md-4 ml-5 my-3 chef-name">
                <h4 class="name"> <%= link_to chef.chefname, chef_path(chef) %></h4>
                <p><%= pluralize(chef.recipes.count, "recipe") if chef.recipes %></p>
                <% if logged_in? && current_chef.admin? && !chef.admin? %>
                <%= link_to 'delete this chef', chef_path(chef), method: :delete, data: {confirm: 'Are you sure? Your account and your recipes will be deleted'}, class:"small text-secondary text-uppercase" %>
                <% end %>
            </div>

        </div>


        <% end %>
        <%= will_paginate list_classes: %w(pagination justify-content-center mt-2)%>
    </div>
</div>

app/views/chefs/new.html.erb
<div class="row my-5">
    <div class="col-md-6 offset-md-3">
        <%= render 'form' %>
    </div>
</div>

app/views/chefs/show.html.erb
<div class="row">
    <div class="col-md-10 offset-md-1">
        <div class="text-center">
            <h2 class="mb-3">Chef <%= @chef.chefname %>'s Profile </h2>
            <%= gravatar_for @chef, size: 150 %>
            <p class="text-uppercase mt-3"><%= @chef.chefname %></p>
            <% if logged_in? && current_chef == @chef %>
            <%= link_to 'Edit Your Profile', edit_chef_path(current_chef) %>
            <% end %>
        </div>
        <hr>
        <%= will_paginate @chef_recipes, list_classes: %w(pagination justify-content-center mt-2 mb-4) %>
        <%= render 'recipes/recipe', obj: @chef_recipes %>
    </div>
</div>