config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  get 'pages/home', to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :recipes do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :delete]
  end
  
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  resources :ingredients, except: [:destroy]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'

  resources :messages, only: [:create]

end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, presence: true
    before_save { self.name = name.titlecase }
    validates :description, presence: true, length: {minimum: 5, maximum: 500}
    belongs_to :chef
    validates :chef_id, presence: true
    default_scope -> {order(updated_at: :desc)}
    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :set_recipe, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @recipes = Recipe.paginate(page: params[:page], per_page: 5)
    end

    def show
        @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
        @comment = Comment.new
    end

    def new
        @recipe = Recipe.new
        @recipes = Recipe.all
    end

    def create 
        @recipe = Recipe.new(recipe_params)
        @recipe.chef = current_chef
        if @recipe.save
            flash[:success] = "Recipe was created"
            redirect_to recipe_path(@recipe)
        else
            render 'new'
        end
    end

    def edit
    end 

    def update 
        if @recipe.update(recipe_params)
            flash[:success] = "Recipe was updated"
            redirect_to recipe_path(@recipe)
        else
            render 'edit'
        end
    end

    def destroy 
        Recipe.find(params[:id]).destroy
        flash[:success] = "Recipe was deleted"
        redirect_to recipes_path
    end

    private
    def set_recipe
        @recipe = Recipe.find(params[:id])
    end

    def recipe_params
        params.require(:recipe).permit(:name, :description, ingredient_ids: [])
    end

    def require_same_user
        if current_chef != @recipe.chef and !current_chef.admin? 
            byebug
            flash[:danger] = "You can only edit or delete your own recipes"
            redirect_to recipes_path
        end
    end
end

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe|%>
<div class="row border-bottom m-3">
    <div class="col-md-4">
    </div>
    <div class="col-md-8">
        <h5 class="name"> <%= link_to recipe.name, recipe_path(recipe) %></h5>
        <p> <%= recipe.description %></p>
        <% if recipe.ingredients.any? %>
        <p><span class="small">Ingredients:</span> <%= render recipe.ingredients %></p>
        <% end %>
        <p><span class="small text-danger text-uppercase">By <%= link_to recipe.chef.chefname, chef_path(recipe.chef), class:"text-danger" %></span>
            <span class="small text-secondary text-bold"> | <%= recipe.chef.created_at.strftime("%m.%d.%Y") %></span>
            <span class="small text-secondary text-bold">| <%= pluralize(recipe.comments.count, 'Comment') %></span></p>
        <% if logged_in? && (recipe.chef == current_chef || current_chef.admin? ) %>

        <p class="small"><%= link_to 'Edit your recipe', edit_recipe_path(recipe) %><span class="px-3 text-secondary">|</span><%= link_to 'Delete your recipe', recipe_path(recipe), method: :delete, data: {confirm: 'Are you sure'} %></p>
        <% end %>
    </div>
</div>

<% end %>

app/views/recipes/_recipe_form.html.erb
<%= render 'shared/errors', obj:@recipe %>
<% if logged_in? %>
<div class="row">
    <div class="col-md-8 offset-md-2">
        <h2 class="mb-4"><%= title %></h2>
        <%= form_for @recipe do |f| %>
        <div class="form-group">
            <%= f.text_field :name, class:"form-control", placeholder:"Recipe name"%>
        </div>
        <div class="form-group">
            <%= f.text_area :description, class:"form-control", placeholder:"Recipe description", rows:"7" %>
        </div>
        <div class="form-group">
            <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb|%>
            <% cb.label(class:"checkbox-inline input-checkbox mr-3") {cb.check_box(class:"checkbox mr-1")+cb.text }%>
            <% end %>

        </div>
        <%= f.submit class:"btn btn-danger" %>
        <% end %>
        <div class="mt-5 text-secondary text-center cancel-request-link">
            [ <%= link_to 'Cancel Request and Return to Recipes Listing', recipes_path, class:'text-secondary' %>]
        </div>
    </div>
</div>
</div>
<% else %>
<div class="row">
    <div class="col-md-6 offset-md-3 mb-5">
        <p>You need to log in to enter a new recipe</p>
        <%= render 'chefs/login_and_signup_form'%>
    </div>
</div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'recipe_form', title: 'Edit Recipe' %>

app/views/recipes/index.html.erb
    <h2 class="mt-3 line">All Recipes</h2>
    <div class="row">
        <div class="col-md-12">
            <%= will_paginate list_classes: %w(pagination justify-content-center mt-2)%>
        </div>
    </div>
    <%= render 'recipe', obj: @recipes %>
    <div class="row">
        <div class="col-md-12">
            <%= will_paginate list_classes: %w(pagination justify-content-center mt-2)%>
        </div>
    </div>

app/views/recipes/new.html.erb
<%= render 'recipe_form', title:'New Recipe' %>

app/views/recipes/show.html.erb
<div class="row m-5">
    <div class="col-md-8 offset-md-2 text-center">
        <p class="small text-left mb-4"><%= link_to 'Back to Recipes List', recipes_path %></p>
        <h2 class="mb-4"><%= @recipe.name %></h2>
        <p class="lead"><%= simple_format(@recipe.description) %></p>
        <% if @recipe.ingredients.any? %>
        <p><span class="small">Ingredients:</span> <%= render @recipe.ingredients %></p>
        <% end %>
        <p><%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %></p>
        <p class="mb-1 small text-uppercase">By <%= @recipe.chef.chefname %></p>
        <p class="small text-secondary text-bold"><%= @recipe.chef.created_at.strftime("%B %d, %Y") %></p>
        <%= render 'shared/like', obj:@recipe %>
        <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>

        <p class="small"><%= link_to 'Edit your recipe', edit_recipe_path(@recipe) %><span class="px-3 text-secondary">|</span><%= link_to 'Delete your recipe', recipe_path(@recipe), method: :delete, data: {confirm: 'Are you sure'} %></p>
        <% end %>
    </div>
</div>

<div class="row">
    <div class="col-md-6 offset-md-3">
        <% if logged_in?%>
        <%= form_for([@recipe, @comment], remote: true) do |f| %>
        <div class="form-group">
            <%= f.text_area :description, class:"form-control", rows: 4, placeholder:"Any comments?"%>
        </div>
        <%= f.submit 'Post', class:"btn btn-danger" %>
        <% end %>
        <% end %>
    </div>
</div>


<% if @recipe.comments !=0 %>
<div class="row">
    <div class="col-md-6 offset-md-3 mb-5">
        <hr>
        <p class="mb-3 text-secondary">Comments:</p>
        <div id="comments">
            <div id="messages">
                <%= render partial: 'comments/comments', object: @comments %>
            </div>
        </div>
    </div>
</div>
<% end %>