config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  get 'pages/home', to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :recipes do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :delete]
  end
  
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  resources :ingredients, except: [:destroy]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'

  resources :messages, only: [:create]

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    validates :name, presence: true, length: {minimum: 3, maximum: 40}
    before_save { self.name = name.titlecase }
    validates_uniqueness_of :name
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    before_action :set_ingredient, only: [:edit, :update, :show]
    before_action :require_user, except: [:index, :show]
    before_action :require_admin, except: [:index, :show]

    def new
        @ingredient = Ingredient.new
    end

    def create
        @ingredient = Ingredient.new(ingredient_params)
        if @ingredient.save
            flash[:success] = "Ingredient was created"
            redirect_to ingredient_path(@ingredient)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @ingredient.update(ingredient_params)
            flash[:success] = "Ingredient was updated"
            redirect_to @ingredient
        else
            render 'edit'
        end
    end

    def show
        @ingredient_recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 5)
    end

    def index
        @ingredients = Ingredient.paginate(page: params[:page], per_page: 5)
    end

    private

    def set_ingredient
        @ingredient = Ingredient.find(params[:id].capitalize)
    end

    def ingredient_params
        params.require(:ingredient).permit(:name)
    end

    def require_admin
        if logged_in? && !current_chef.admin?
            flash[:danger] = "Only admin users can perform that action"
            redirect_to ingredients_path
        end 
    end

end

app/views/ingredients/_ingredient.html.erb
<span class="badge badge-light mr-1"><%= link_to ingredient.name, ingredient_path(ingredient)%></span>

app/views/ingredients/_ingredient_form.html.erb
<%= render 'shared/errors', obj:@ingredient %>
<% if logged_in? %>
<div class="row">
    <div class="col-md-8 offset-md-2">
        <h2 class="mb-4"><%= title %></h2>
        <%= form_for @ingredient do |f| %>
        <div class="form-group">
            <%= f.text_field :name, class:"form-control", placeholder:"Ingredient name"%>
        </div>
        <%= f.submit(@ingredient.new_record? ? "Add Ingredient" : "Update Ingredient", class:"btn btn-danger") %>

        <% end %>
        <div class="mt-5 text-secondary text-center cancel-request-link">
            [ <%= link_to 'Cancel Request and Return to Ingredients Listing', ingredients_path, class:'text-secondary' %>]
        </div>
    </div>
</div>
</div>
<% else %>
<div class="row">
    <div class="col-md-6 offset-md-3 mb-5">
        <p>You need to log in to enter a new ingredient</p>
        <%= render 'chefs/login_and_signup_form'%>
    </div>
</div>
<% end %>

app/views/ingredients/edit.html.erb
<%= render 'ingredients/ingredient_form', title:'Edit Ingredient' %>

app/views/ingredients/index.html.erb
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2 class="mt-3 line">All Ingredients</h2>
        <%= will_paginate list_classes: %w(pagination justify-content-center mt-2)%>
        <% @ingredients.each do |ingredient|%>
        <div class="row border-bottom m-3">
            <div class="col-md-6 ml-5 my-3 chef-name">
                <h4 class="name"> <%= link_to ingredient.name, ingredient_path(ingredient) %></h4>
                <p><%= pluralize(ingredient.recipes.count, "recipe") if ingredient.recipes %></p>
                <% if logged_in? && current_chef.admin? %>
                <%= link_to 'edit this ingredient', edit_ingredient_path(ingredient), class:"small text-secondary text-uppercase" %>
                <% end %>
            </div>

        </div>


        <% end %>
        <%= will_paginate list_classes: %w(pagination justify-content-center mt-2)%>
    </div>
</div>

app/views/ingredients/new.html.erb
<%= render 'ingredients/ingredient_form', title:'New Ingredient' %>

app/views/ingredients/show.html.erb
<div class="row">
    <div class="col-md-10 offset-md-1">
        <div class="text-center">
            <h2 class="mb-3"><%= @ingredient.name.titleize %>
                <% if logged_in? && current_chef.admin? %>
                <span class="h6 ml-2 font-weight-light"><%= link_to 'Edit', edit_ingredient_path(@ingredient), class:"small"%></span>
                <% end %>
            </h2>
            <p class="text-uppercase small mt-3">Recipes with <%= @ingredient.name %></p>
            <% if logged_in? && current_chef == @chef %>
            <%
=begin%>
            <%= link_to 'Edit Your Profile', edit_chef_path(current_chef) %>
            <%
=end%>
            <% end %>
        </div>
        <hr>
        <% if @ingredient.recipes.count != 0 %>
        <%= will_paginate @ingredient_recipes, list_classes: %w(pagination justify-content-center mt-2 mb-4) %>
        <% end %>
        <%
=begin%>
        <%= render 'recipes/recipe', obj: @chef_recipes %>
        <%
=end%>
        <%= render 'recipes/recipe', obj: @ingredient_recipes %>
    </div>
</div>