config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  get 'pages/home', to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :recipes do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :delete]
  end
  
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  resources :ingredients, except: [:destroy]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'

  resources :messages, only: [:create]

end

app/views/layouts/_footer.html.erb
<footer class="container-fluid py-5">
  <div class="row">
    <div class="col-12 col-md">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24" focusable="false"><title>Product</title><circle cx="12" cy="12" r="10"/><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"/></svg>
      <small class="d-block mb-3 text-muted">&copy; 2017-2020</small>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Cool stuff</a></li>
        <li><a class="text-muted" href="#">Random feature</a></li>
        <li><a class="text-muted" href="#">Team feature</a></li>
        <li><a class="text-muted" href="#">Stuff for developers</a></li>
        <li><a class="text-muted" href="#">Another one</a></li>
        <li><a class="text-muted" href="#">Last time</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Resource</a></li>
        <li><a class="text-muted" href="#">Resource name</a></li>
        <li><a class="text-muted" href="#">Another resource</a></li>
        <li><a class="text-muted" href="#">Final resource</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Resources</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Business</a></li>
        <li><a class="text-muted" href="#">Education</a></li>
        <li><a class="text-muted" href="#">Government</a></li>
        <li><a class="text-muted" href="#">Gaming</a></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><a class="text-muted" href="#">Team</a></li>
        <li><a class="text-muted" href="#">Locations</a></li>
        <li><a class="text-muted" href="#">Privacy</a></li>
        <li><a class="text-muted" href="#">Terms</a></li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
 <div class="row mt-5">
     <div class="col-md-8 offset-md-2">
         <% flash.each do |name, msg| %>
         <div class="alert alert-<%= name %>">
             <a href="#" class="close" data-dismiss="alert">&#215;</a>
             <%= msg %>
         </div>
         <% end %>
     </div>
 </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-orange navbar-light">
    <div class="container">
        <%= link_to "Myrecipes", root_path, class: "navbar-brand", id: "logo" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <%= link_to raw('Recipes<span class="sr-only">(current)</span>'), recipes_path, class: "nav-link" %>
                </li>
                <% if logged_in? %>
                <li class="nav-item">
                    <%= link_to 'New Recipe', new_recipe_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Chatroom', chat_path, class:"nav-link" %>
                </li>
                <% end %>

                <li class="nav-item">
                    <%= link_to 'Chefs', chefs_path, class: "nav-link" %>
                </li>

                <li class="nav-item dropdown">
                    <div class="nav-link dropdown-toggle" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= link_to 'Ingredients', ingredients_path%>
                    </div>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
                        <%= link_to 'All ingredients', ingredients_path, class:"dropdown-item" %>
                        <div class="dropdown-divider"></div>
                        <% Ingredient.all.each do |ingredient|%>
                        <%= link_to ingredient.name.capitalize, ingredient_path(ingredient), class:"dropdown-item" %>
                        <% end %>
                        <% if logged_in? && current_chef.admin? %>
                        <div class="dropdown-divider"></div>
                        <%= link_to 'New Ingredient', new_ingredient_path, class:"dropdown-item" %>
                        <% end %>
                    </div>
                </li>

            </ul>
            <form class="form-inline d-flex my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <ul class="navbar-nav ml-auto">
                <% if logged_in? %>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= current_chef.chefname.capitalize %><span class="pl-1"><%= "Admin" if current_chef.admin? %>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%= link_to 'Create New Recipe', new_recipe_path, class:"dropdown-item" %>
                        <%= link_to 'Profile', chef_path(current_chef), class:"dropdown-item" %>
                        <div class="dropdown-divider"></div>
                        <%= link_to 'Log out', logout_path, method: :delete, class:"dropdown-item" %>
                    </div>
                </li>
                <% else %>
                <li class="nav-item">
                    <%= link_to 'Login', login_path, class:"btn btn-danger" %>
                </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Myrecipes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render 'layouts/navigation' %>
    <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    </>

</html>